Add docker
EvgenyBelykh/java-shareit pull request #4
Opened 2023-02-08 18:42 UTC by EvgenyBelykh

2023-02-09 16:23 UTC, EvgenyKoptubenko commented
Есть замечания по прошлым итерациям.
Добавь обработку сообщений для клиента, когда присылается пользователь второй раз
Сейчас приходит 500 
{
	"error": "Неверный запрос: could not execute statement; SQL [n/a]; constraint [users_email_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
}

На самом деле 500- ошибки на стороне сервера, а тут никакой ошибки на сервере не должно быть, а должен прийти Conflict.

2023-02-09 16:27 UTC, EvgenyKoptubenko commented
Добавь обработчик того, что приходит неверный email. Клиенту не нужно такого длинное сообщение
{
	"error": "Неверный запрос: Validation failed for argument [0] in public org.springframework.http.ResponseEntity<java.lang.Object> ru.practicum.shareit.user.UserController.add(ru.practicum.shareit.user.dto.UserRequestDto) with 2 errors: [Field error in object 'userRequestDto' on field 'email': rejected value [email3email.com]; codes [Email.userRequestDto.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userRequestDto.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@5173f524,.*]; default message [must be a well-formed email address]] [Field error in object 'userRequestDto' on field 'name': rejected value [null]; codes [NotBlank.userRequestDto.name,NotBlank.name,NotBlank.java.lang.String,NotBlank]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userRequestDto.name,name]; arguments []; default message [name]]; default message [must not be blank]] "
}

2023-02-09 16:30 UTC, EvgenyKoptubenko commented
Если создать Items штук 6, потом на них повесить Bookings, то все равно в Items приходят null (Но тут может быть я что-то не учел, чтобы эти данные начали появляться. Так что это может быть и не замечание)
[
	{
		"id": 1,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	},
	{
		"id": 2,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	},
	{
		"id": 3,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	},
	{
		"id": 4,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	},
	{
		"id": 5,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	},
	{
		"id": 6,
		"name": "nameItem",
		"description": "descriptionItem",
		"available": true,
		"lastBooking": null,
		"nextBooking": null,
		"comments": null,
		"requestId": null
	}
]

2023-02-09 16:34 UTC, EvgenyKoptubenko requested changes
По докеру замечаний нет, есть небольшие предложения по улучшению кода с предыдущих итераций

2023-02-10 22:02 UTC, EvgenyBelykh commented
Пришлось добавить небольшой костыль из-за неправильно составленного теста постмена. В комментарии в коде это указал. 
При бронировании необходимы еще пользователи, которые владеют вещью и которые бронируют вещи. Проверил еще раз,  items в бронировании отображаются.

2023-02-11 17:35 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-03-01 19:50 UTC, merged